# Generated by Django 3.1.7 on 2021-05-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagemodel',
        ),
    ]
